/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/consumer`; params?: Router.UnknownInputParams; } | { pathname: `/Consumerpage`; params?: Router.UnknownInputParams; } | { pathname: `/distributor`; params?: Router.UnknownInputParams; } | { pathname: `/Distributorpage`; params?: Router.UnknownInputParams; } | { pathname: `/farmer`; params?: Router.UnknownInputParams; } | { pathname: `/Farmerpage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/retailer`; params?: Router.UnknownInputParams; } | { pathname: `/Retailerpage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/consumer`; params?: Router.UnknownOutputParams; } | { pathname: `/Consumerpage`; params?: Router.UnknownOutputParams; } | { pathname: `/distributor`; params?: Router.UnknownOutputParams; } | { pathname: `/Distributorpage`; params?: Router.UnknownOutputParams; } | { pathname: `/farmer`; params?: Router.UnknownOutputParams; } | { pathname: `/Farmerpage`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/retailer`; params?: Router.UnknownOutputParams; } | { pathname: `/Retailerpage`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/consumer${`?${string}` | `#${string}` | ''}` | `/Consumerpage${`?${string}` | `#${string}` | ''}` | `/distributor${`?${string}` | `#${string}` | ''}` | `/Distributorpage${`?${string}` | `#${string}` | ''}` | `/farmer${`?${string}` | `#${string}` | ''}` | `/Farmerpage${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/retailer${`?${string}` | `#${string}` | ''}` | `/Retailerpage${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/consumer`; params?: Router.UnknownInputParams; } | { pathname: `/Consumerpage`; params?: Router.UnknownInputParams; } | { pathname: `/distributor`; params?: Router.UnknownInputParams; } | { pathname: `/Distributorpage`; params?: Router.UnknownInputParams; } | { pathname: `/farmer`; params?: Router.UnknownInputParams; } | { pathname: `/Farmerpage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/retailer`; params?: Router.UnknownInputParams; } | { pathname: `/Retailerpage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
