/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ConsumerPage`; params?: Router.UnknownInputParams; } | { pathname: `/DistributorPage`; params?: Router.UnknownInputParams; } | { pathname: `/Farmerpage`; params?: Router.UnknownInputParams; } | { pathname: `/Forgetpasswordpage`; params?: Router.UnknownInputParams; } | { pathname: `/GetStartedPage`; params?: Router.UnknownInputParams; } | { pathname: `/Retailerpage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/signinPage`; params?: Router.UnknownInputParams; } | { pathname: `/signuppage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/ConsumerPage`; params?: Router.UnknownOutputParams; } | { pathname: `/DistributorPage`; params?: Router.UnknownOutputParams; } | { pathname: `/Farmerpage`; params?: Router.UnknownOutputParams; } | { pathname: `/Forgetpasswordpage`; params?: Router.UnknownOutputParams; } | { pathname: `/GetStartedPage`; params?: Router.UnknownOutputParams; } | { pathname: `/Retailerpage`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/signinPage`; params?: Router.UnknownOutputParams; } | { pathname: `/signuppage`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/ConsumerPage${`?${string}` | `#${string}` | ''}` | `/DistributorPage${`?${string}` | `#${string}` | ''}` | `/Farmerpage${`?${string}` | `#${string}` | ''}` | `/Forgetpasswordpage${`?${string}` | `#${string}` | ''}` | `/GetStartedPage${`?${string}` | `#${string}` | ''}` | `/Retailerpage${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/signinPage${`?${string}` | `#${string}` | ''}` | `/signuppage${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ConsumerPage`; params?: Router.UnknownInputParams; } | { pathname: `/DistributorPage`; params?: Router.UnknownInputParams; } | { pathname: `/Farmerpage`; params?: Router.UnknownInputParams; } | { pathname: `/Forgetpasswordpage`; params?: Router.UnknownInputParams; } | { pathname: `/GetStartedPage`; params?: Router.UnknownInputParams; } | { pathname: `/Retailerpage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/signinPage`; params?: Router.UnknownInputParams; } | { pathname: `/signuppage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
