/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Consumerpage`; params?: Router.UnknownInputParams; } | { pathname: `/Distributorpage`; params?: Router.UnknownInputParams; } | { pathname: `/Farmerpage`; params?: Router.UnknownInputParams; } | { pathname: `/forgetpasswordpage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Retailerpage`; params?: Router.UnknownInputParams; } | { pathname: `/signinPage`; params?: Router.UnknownInputParams; } | { pathname: `/signuppage`; params?: Router.UnknownInputParams; } | { pathname: `/../Components/AppHeader`; params?: Router.UnknownInputParams; } | { pathname: `/LandingPage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Consumerpage`; params?: Router.UnknownOutputParams; } | { pathname: `/Distributorpage`; params?: Router.UnknownOutputParams; } | { pathname: `/Farmerpage`; params?: Router.UnknownOutputParams; } | { pathname: `/forgetpasswordpage`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/Retailerpage`; params?: Router.UnknownOutputParams; } | { pathname: `/signinPage`; params?: Router.UnknownOutputParams; } | { pathname: `/signuppage`; params?: Router.UnknownOutputParams; } | { pathname: `/../Components/AppHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/LandingPage`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/Consumerpage${`?${string}` | `#${string}` | ''}` | `/Distributorpage${`?${string}` | `#${string}` | ''}` | `/Farmerpage${`?${string}` | `#${string}` | ''}` | `/forgetpasswordpage${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/Retailerpage${`?${string}` | `#${string}` | ''}` | `/signinPage${`?${string}` | `#${string}` | ''}` | `/signuppage${`?${string}` | `#${string}` | ''}` | `/../Components/AppHeader${`?${string}` | `#${string}` | ''}` | `/LandingPage${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Consumerpage`; params?: Router.UnknownInputParams; } | { pathname: `/Distributorpage`; params?: Router.UnknownInputParams; } | { pathname: `/Farmerpage`; params?: Router.UnknownInputParams; } | { pathname: `/forgetpasswordpage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Retailerpage`; params?: Router.UnknownInputParams; } | { pathname: `/signinPage`; params?: Router.UnknownInputParams; } | { pathname: `/signuppage`; params?: Router.UnknownInputParams; } | { pathname: `/../Components/AppHeader`; params?: Router.UnknownInputParams; } | { pathname: `/LandingPage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Consumerpage`; params?: Router.UnknownInputParams; } | { pathname: `/Distributorpage`; params?: Router.UnknownInputParams; } | { pathname: `/Farmerpage`; params?: Router.UnknownInputParams; } | { pathname: `/LandingPage`; params?: Router.UnknownInputParams; } | { pathname: `/Retailerpage`; params?: Router.UnknownInputParams; } | { pathname: `/forgetpasswordpage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/signinPage`; params?: Router.UnknownInputParams; } | { pathname: `/signuppage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Consumerpage`; params?: Router.UnknownOutputParams; } | { pathname: `/Distributorpage`; params?: Router.UnknownOutputParams; } | { pathname: `/Farmerpage`; params?: Router.UnknownOutputParams; } | { pathname: `/LandingPage`; params?: Router.UnknownOutputParams; } | { pathname: `/Retailerpage`; params?: Router.UnknownOutputParams; } | { pathname: `/forgetpasswordpage`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/signinPage`; params?: Router.UnknownOutputParams; } | { pathname: `/signuppage`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/Consumerpage${`?${string}` | `#${string}` | ''}` | `/Distributorpage${`?${string}` | `#${string}` | ''}` | `/Farmerpage${`?${string}` | `#${string}` | ''}` | `/LandingPage${`?${string}` | `#${string}` | ''}` | `/Retailerpage${`?${string}` | `#${string}` | ''}` | `/forgetpasswordpage${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/signinPage${`?${string}` | `#${string}` | ''}` | `/signuppage${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Consumerpage`; params?: Router.UnknownInputParams; } | { pathname: `/Distributorpage`; params?: Router.UnknownInputParams; } | { pathname: `/Farmerpage`; params?: Router.UnknownInputParams; } | { pathname: `/LandingPage`; params?: Router.UnknownInputParams; } | { pathname: `/Retailerpage`; params?: Router.UnknownInputParams; } | { pathname: `/forgetpasswordpage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/signinPage`; params?: Router.UnknownInputParams; } | { pathname: `/signuppage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
